In [ ]:
import pandas as pd
from matplotlib import pyplot as plt
import plotly.express as px
import dash
import plotly.graph_objects as go 
import pgeocode
from dash import Dash, html, dcc, Output, Input, callback
#importing everything I will need

In [2]:
intapp = pd.read_csv('Internship Applications_cleanish.csv')
intapp.tail() # I checked head and it showed the first 5, i just wanted to make sure it was 
#showing the most current which it is, I don't remember doing .tail i class but it's what seemed
#logical to me and it worked

,Submission Date,Advising \nApproval Response,Advising Approval \nResponse Date,Advising Comments,Advisor,Internship Coordinator \nApproval Response,Internship Coordinator \nApproval Response Date,Internship Coordinator Comments,Internship Coordinator,Advising/Tyler Registration Comments,...,Total Work Hours for Semester,Requested Credit Hours,"In-person, Remote, Hybrid",Paid Internship?,Salary,Internship Job Title,Description of Job Responsibilities,How will the internship prepare them for professional practice in their major?,Offered a permanent position (Y/N)?,Accepted permanent position (Y/N)?
942,4/18/26,Approve,2026-04-20T14:17:08Z,NaN,"Hansen, Ellie",Approve,2026-04-20T15:00:18Z,"Please register for 1 credit, summer 2026, BUS...","Knepper, Caitlin",registered for bus 40192-30,...,10.0,1.0,Hybrid,No,NaN,Social Media Marketing Intern,"Assist with creating, scheduling and publishin...",This will help me prepare for what I want to p...,NaN,NaN
943,4/21/26,Approve,2026-04-21T17:06:31Z,NaN,"Hansen, Ellie",Approve,2026-04-21T17:11:54Z,NaN,"Knepper, Caitlin",NaN,...,150.0,1.0,Hybrid,Yes,50$ per article,Reporter,Reporting on issues and events in Portage coun...,"As a journalism major, it is important that I ...",NaN,NaN
944,4/22/26,Approve,2026-04-22T14:17:48Z,NaN,"Hansen, Ellie",Approve,2026-04-22T15:28:22Z,"Confirmed with Tessa, switch to 1 credit","Jeffries, Lauren",NaN,...,150.0,2.0,In-person,No,NaN,Operations and Marketing Intern,"Creating posters/flyers for local bands, makin...",It will be a great way to make connections and...,NaN,NaN
945,4/23/26,N/A - EMAT Graduate Program,N/A - EMAT Graduate Program,N/A - EMAT Graduate Program,N/A - EMAT Graduate Program,Approve,2026-04-24T13:25:14Z,NaN,"Dowling, Kristin",NaN,...,135.0,3.0,In-person,Yes,$15 per hour,Content Producer,planning esports video and content (long form)...,"Everything I will be doing in this internship,...",NaN,NaN
946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
len(intapp) # I want to know the number of applications

947

In [4]:
intapp.columns #I wanted to make sure I know all of the columns and need to decide which are most interesting
#I know the school director wants to see where students are getting internships, I think it would be good to see 
# the numbers of students getting internships by year (but maybe not) I did add the last 2 columns which we do not currently track so these are fake

Index(['Submission Date', 'Advising \nApproval Response',
       'Advising Approval \nResponse Date', 'Advising Comments', 'Advisor',
       'Internship Coordinator \nApproval Response',
       'Internship Coordinator \nApproval Response Date',
       'Internship Coordinator Comments', 'Internship Coordinator',
       'Advising/Tyler Registration Comments', 'Registration Date',
       'Semester Student Registered', 'Student \nFirst Name',
       'Student \nLast Name', 'KSU Email', 'Phone Number', 'CCI Major',
       'Organization Name', 'Description of Organization',
       'Organization Street Address', 'Organization City',
       'Organization State', 'Organization Country (if applicable)',
       'Organization Zip', 'Organization Contact Info', 'Organization Website',
       'Supervisor Name', 'Supervisor Email', 'Supervisor Phone Number',
       'Supervisor Job Title', 'Internship Start Date', 'Internship End Date',
       'Total Number of Weeks Working', 'Work Hours Per Week',
       'Total Work Hours for Semester', 'Requested Credit Hours',
       'In-person, Remote, Hybrid', 'Paid Internship?', 'Salary',
       'Internship Job Title', 'Description of Job Responsibilities',
       'How will the internship prepare them for professional practice in their major?',
       'Offered a permanent position (Y/N)?',
       'Accepted permanent position (Y/N)?'],
      dtype='object')

In [5]:
type(intapp['Organization Name'].iloc[0])

str

In [6]:
intappdata = pd.DataFrame(intapp['Paid Internship?']) #how do I see if students were paid

intappdata.head(10)

  Paid Internship?
0               No
1              Yes
2              Yes
3               No
4              Yes
5              Yes
6              Yes
7               No
8               No
9              Yes

In [ ]:
len(intapp['Paid Internship?'])
#duh this is the same

947

In [57]:
paid_unpaid = intapp.groupby('Paid Internship?').size().sort_values()

In [ ]:
fig1 = go.Figure(data=[go.Pie(labels=paid_unpaid.index,values=paid_unpaid.values,title='Paid Internship?')])

fig1.show()
#pie chart might be inreresting to see but it would be better if more were paid

In [ ]:
intappdata = pd.DataFrame(intapp['Organization Name']) 

intappdata.head(10)
#how do I get the number of unique names?

                                   Organization Name
0  KSU / CAPS - Counseling and Psychological serv...
1                                         Mail Pro 1
2                     Stow Munroe Falls City Schools
3                                         Kent Wired
4                 KENT STATE ATHLETIC COMMUNICATIONS
5       KSU/College of Communication and Information
6                                   Playhouse Square
7                           West County News Journal
8                              Christ Baptist Church
9                                              Fox 8

In [ ]:
intapp['Organization Name'].nunique()
#chatgpt told me this was the way to find the number of unique names so of my 947 applications, 664 which I still question

664

In [12]:
intapp['Organization Name'].unique()

array(['KSU / CAPS - Counseling and Psychological services ',
       'Mail Pro 1', 'Stow Munroe Falls City Schools', 'Kent Wired',
       'KENT STATE ATHLETIC COMMUNICATIONS',
       'KSU/College of Communication and Information', 'Playhouse Square',
       'West County News Journal', 'Christ Baptist Church', 'Fox 8',
       'Akron Recording Company', 'Kent State University',
       'Crisis Prevention Institute', 'Ohio Domestic Violence Network',
       'Akron Life Magazine', 'Oriana House',
       'KCD Worldwide Public Relations',
       "SJS Enterprises 426 DBA: Teresa's Pizza",
       'The Pittsburgh Penguins',
       'Kent State Recreation and Wellness Services', 'GRS Recruiting',
       'SpartanNash', "La'Lew Public Relations",
       'Minor Football League (Cleveland Outlaws)',
       'Columbus Christian Center', 'Charles Osowik Management',
       'Todd Biss Productions', 'Summit County Parole Office',
       'Jumpstart Video Productions', '427 Studios',
       'National Multiple Sclerosis Society', 'RH',
       'Classic Teleproductions', 'Sports Media Inc.',
       'POW Motorsports, Driver for Arrow McLaren INDYCAR ',
       'Keegan Larwin Creative',
       'Colonel Pamela Stevenson for Attorney General',
       'MAPS air museum ', 'Faith Family ', 'Mindhome Inc', 'IdeaBase',
       'Kent State Division of Diversity, Equity, and Inclusion',
       'Signum Design', 'Hop Tree Brewing', 'Cleveland Magazine',
       'Cleveland Metropolitan Bar Association',
       'The World Music Foundation ', "Ohio's News Connection",
       'Yiddishland Calfornia', 'Incept Advertising Services',
       'DDO Artists Agency', 'Camp Winnebago',
       'Kent State Library Communications ',
       'College of Education, Health, and Human Services',
       'SLA Video Productions',
       'Kent State University Athletics Marketing Department ',
       'Emily Roggenburk', 'Mosher Media', 'Canton Harbor High School',
       'Kent State Football', 'Humanoids', 'Sherwin Williams', 'PARTA',
       'KSU/Division of I.T.', 'CLE Cotton Candy ',
       'Kent State Center for Teaching and Learning', 'Sierra Lobo',
       'Engaged With Nora',
       'Kent State University College Technology, Media, and Design Team',
       'KSU /  Housing & Culinary Services', 'Positive Masculinity Now',
       'Golden Flash T.V', 'MidTown Cleveland Inc.',
       'PBS Western Reserve', 'Gameday Sportwear',
       'Portage County Regional Planning Commission ', 'CD 92.9 FM ',
       'Work Shed Weddings', 'Akron Beacon Journal', 'American High',
       'Goldberg Companies Incorperated', 'Employers Health',
       'Division of Philanthropy and Alumni Engagement',
       'LaunchNET Kent State', 'GBCS', 'Castix LLC', 'Kent State UCM',
       'Akron Rubber Ducks', 'Purveyour Inc. ', 'Hello LLC',
       'Savannah Bananas', 'NBC News - KMIR TV', 'ESPN Cleveland ',
       'Fairlawn Country Club', 'Gold Arrow Camp',
       'Inside Gymnastics Magazine', 'FHI 360',
       'National Inventors Hall of Fame',
       'Case Western Reserve University School of Medicine ',
       'Superior Beverage Group', 'PALO Creative',
       'Kent State University Student Media Office', 'WEDOhio', 'WFMJ',
       'Clark-Reliance ', 'LeBron James Family Foundation',
       "L'Officiel USA", 'NPi Audio Visual Solutions',
       'Kent State University Center for Public Policy and Health',
       'Ohio Aluminum ', 'Rebecca Adele PR & Events',
       'Kent State Student Media ', 'OSV Studios',
       'Lush Salon Spa and Nails', 'Destination Cleveland ',
       'The First Tee of Cleveland ', 'Voice of America', 'Lucky Shoes',
       'Arbors at Stow', 'Z.Leads Media LLC', 'Florida Voices for Health',
       'Lake Erie Crushers', 'Born Products', 'Davey Tree',
       'Zygote Press', 'TurnUp Youth Activism ',
       'BBC News and NewsNation', 'Washington Wildthings',
       'KSU / Center for Sexual and Relationship Violence Support Services',
       'Listen in With KNN x Fox Sports Radio ',
       "Christian Children's Home of Ohio", 'StageWorx',
       'Transition Studios', '10k Movement', 'KSU / NewsLab',
       'martinwolf', 'TheraPanacea', 'Ideastream Public Media',
       'Astro Creative', 'Landon For Ohio', 'Jake Cole Films',
       'The Gathering', '1895 Films ', 'North Canton Chapel ',
       'Lake County Captains', 'GIE Media Inc.', 'Vitamix ',
       'BG Falcon Media', 'Art House, Inc.', '1895 Films',
       'Kent State Teleprodutions ',
       'GIE Media - Golf Course Industry Magazine',
       'Ohio Department of Transportation ', 'Bath & Body Works',
       'The Grog Shop', 'The Grand Resort', 'Ohio Magazine', 'CCL Design',
       'Pando Pub Group', 'Westfield Insurance ', 'GNCO Corporation',
       'Master Printing + Mailing', 'Swanson Publishing LLC', 'Moen Inc.',
       'Megan Chicone State Farm Agent', 'Slim & Merz Creative ',
       'Akron Municipal Court ', 'HighKey Agency ', 'Better Kenmore',
       'ISAK ', 'Ohio 3rd Frontier Emerge Inc.', 'Mohawk Industries',
       'Sozo', 'Mahoning Valley Scrappers', 'EDGE',
       'Transform 2 Better Me Inc.', 'EduOpportunity Network',
       'Lake Erie Crushers ', 'GIE Media',
       'The Muskingum County Library System', 'CIX Direct',
       'Gulf Coast Atlantic Conference and Suno Athletics',
       'peaches and cream ', 'WZZM 13 ABC ', 'WFMJ 21 Sports',
       'Sanctuary Software Studio Inc', 'Pleasant Valley Corporation',
       'First Congregational Church of Hudson ', 'Houde Solutions',
       'Hyland Software Inc', 'Cedar Point', 'Engaged with Nora', 'GFTV',
       'Mobile Health Consumer', 'Milwaukee County Executive Office',
       'Krom Kreative ', 'Kirschenbaum Productions',
       'Thomas Steel Strip Corporation', 'Blue Sky Bee Supply',
       'DCS Corp', 'BrandMuscle', 'American Greetings - AG Interactive',
       'The Dennison Railroad Depot Museum',
       'Inspiring Lives Magazine and The Global Sisterhood.',
       'Matilde Carli Communications', 'Veterans Service Commission',
       'Tatum Games LLC', 'M:7 Agency ', 'Mani Pannu Productioins',
       'eComchain', 'Richmond Times-Dispatch', 'Patio Batel', 'GBCS ',
       'Canton Museum of Art', 'Anthony Thomas Advertising',
       'Red Hen Press', 'BAM Advertising',
       'US Army Corps of Engineers, Alum Creek Lake', 'Her Campus Media',
       'Fuzati', 'Nextstar Media Inc, WKBN',
       'Apex Dermatology & Skin Surgery Center',
       'The Business Works Inc.', 'Cleveland Clinic', 'The Impact Group ',
       'Cuyahoga Falls Library', 'OverDrive', 'QuestMark',
       'Halo Foundation', 'Distinction Agency', 'WNIR 100.1',
       'Post Grad Edge', 'Exact Sciences',
       'The Cleveland Museum of Art (The Community Arts Center) ',
       'The Briarwood Healthcare Community',
       'CLEVELAND MUSEUM OF NATURAL HISTORY',
       'The Allegheny Front through the Pittsburgh Media Partnership.',
       'Top of Mind Public Relations', 'Pittsburgh Riverhounds',
       'Canton Roofing Company', 'Centerra Co-op',
       'Sideshow Collectibles', 'Christian cowan',
       'Cleveland Metropolitan School District', 'Virteom LLC',
       'Audio-Technica ', 'The Borgen Project', 'Hola Cultura',
       'AM 1260 The Rock Cleveland Catholic Radio', 'CMP Communications',
       'NOAS', 'Infinite Synergy', 'Little Jacket Design Services',
       'AdAction', 'Cleveland Jewish Publication Company', 'TKG',
       ' In Step With Horses(ISWH) and American Tire Works(ATW)',
       'Audio-Technica', 'NASA GRC', 'VYRE Network', 'Swish Cultures ',
       'HRN Construction', 'Safira Clinical Research',
       'The Chautauquan Daily', 'Valley Freightliner ', 'Merlette',
       'BestLogic Staffing', 'SLA Video Productions ',
       'The GolF Dome and Tanglewood Country Club',
       'Neighborhood Family Practice ', 'Art With Jenny',
       'Kent State Online', 'State Champs', 'Old World Custom Interiors ',
       'Belt Publishing ', 'Kent State Votes', 'Kent State Athletics ',
       'Shape Cleveland', 'Landon for ohio', 'The Walt Disney Company',
       'Globethics', 'Ezurio', 'Alive! Events and Marketing ',
       "Nationwide Children's Hospital", 'International Media Ministries',
       'LG Media', 'Student Accessibility Services Kent Campus  ',
       'Chavi', 'Kleo', 'William Fredrick Clothing', 'Schnabel Studios ',
       'Digital Enterprise Solutions', 'A Magazine ', 'Drips Inc.',
       'Slap Stik Comedy Entertainment', 'Milk And Honey',
       'Beacon Collision Center, LLC',
       "Handel's Homemade Ice Cream & Yogurt",
       'R.A.K E. (Random Acts of Kindness Everywhere', 'Milk and Honey',
       'Network Services Kent State', 'Kent State Esports', 'City of CF',
       'Spotlight Media Network', 'NaoNow', '427 Design',
       'Kent state esports', 'Mood9', 'Kent State Student Media',
       'Kent State Athletics', 'Milk by Mom', 'UnionHome Mortgage ',
       'SponsorUnited', 'Media Rebel', 'red point digital',
       'Health Action Council', 'David Wilson/ illustrator mentorship',
       'Signal Akron', 'Bloom Occupational Therapy',
       'Sustainable Living Guide', 'Kent State University Honors College',
       'WFMJ Sports',
       ' Greater Cleveland Automobile Dealers’ Association (GCADA)',
       'Babcock & Wilcox', 'The Dream Bowl', 'My Community Life Church',
       'WJLA/ABC 7 News DC',
       'College Of Arts and Sciences, Kent State University',
       'DRB Systems', 'Arnoff and Associates, Inc.',
       'Unique Natural Body Esthetics ', 'LV8', 'Wolfscape',
       "Hope For a Cure For Alzheimer's", 'Wick Poetry Center',
       'Two Dee Inc.', 'SlapStik Comedy Entertainment',
       'Cuyahoga County Prosecutors Office  ', 'Tuscarawas County YMCA',
       'University Oaks', 'Tangier Catering',
       'Emerald Hospitality Associates ', 'Dr. Mom Digital Marketing',
       'Riverfront Photography', 'Barstool Sports',
       'Women Speak Up x Abby Soul Production', 'Mecha Media, LLC',
       'A kid again ', 'LaunchArts Media ',
       'Rebecca Adele PR & Events/Avant-Garde Art & Craft Shows/C • L • E Cotton Candy',
       'Rise and Shine Academy ', 'Tito Café, Coffee Shop & Retail',
       'Kent State College of Public Health', 'Beck Center for the Arts',
       'Four Cities Compact @ Wadsworth City Schools (via mood9)',
       'OEOC ', 'Monsters Unlimited', 'Black Valve Media',
       'Joffrey Ballet School', 'Ohio Department of National Resources ',
       'Landon for Ohio', 'Portage County Planning Commission',
       'Kent State University, College of Arts and Sciences',
       'Akron Life Magazine ', 'Premier Printing & Signs Inc.',
       'Sukoon Psychotherapy', 'Rock The House Entertainment',
       'Park Place Technologies', 'The Mental Funny Bone Podcast',
       'Yokohama Theatre Group', 'The Cincinnati Insurance Companies',
       'Family and Community Services', 'Engaged With Nora ',
       'WOUB Public Media', 'University Edge Kent ', 'Crater Bros.',
       'Uline', 'The Halo Foundation', 'American Bankers Association',
       'Springvill Family Dentistry ', 'Donley Holding Company LLC',
       "GIE Media's Golf Course Maintenance", 'Student Success Programs',
       'ATPCO ', 'Great Day Improvements', 'National Aviary ',
       'Britânia Eletrodomésticos', 'Northwestern Mutual ',
       'Portage County Regional Planning Commission', 'Fulzati ',
       'Route 8 Studios', 'Quality of Life, Hope for a Cure for ALZ  ',
       'The Chautauqua Institution',
       'Kent State University Library Student MultiMedia Studio',
       'WFMJ-TV', 'Cleveland Soccer Club or Cleveland SC', 'Permco',
       'Defender Home Advocates', 'College Coaches Showcase Camp',
       'Onramps to Careers', 'Stark Community Foundation ',
       'Sinclair Broadcasting Group (WTOV9)',
       'Kent State University - Office of Intercultural Student Life',
       'Raptor Hollow', 'Green AI Institute.',
       'Mentor Public Schools IT Department',
       'Kent State Athletic Communications', 'Rock and Roll Hall of Fame',
       'CMRubinWorld', 'LUMIS Marketing', 'SAGE Integration',
       'The Impact Group', 'Union Home Mortgage',
       'Holly M Communications ', 'LCBC Church',
       'Allegheny County Parks Department', 'Art House',
       'Oklahoma City Thunder (THE PROFESSIONAL BASKETBALL CLUB, LLC)',
       'The Bussiness Works', 'Scandinavia Service Co',
       'WOIO - Channel 19 Cleveland', 'NGSC Sports ',
       'Diamond Baseball League', 'Building Hope In This City',
       'Launch Arts Media', 'WCVB', 'DHL Supply Chain', 'Kas',
       'Triad Production Group', 'Akron Recording Company ',
       'Pink Lemonade Stand', 'Landon Schroeder',
       'Shadow | Vale Productions', 'Eaton', 'Buckeye Broadband BCSN',
       'Tuscarawas County Health Department ', 'Granex',
       'Center for Aquatic Services', 'Workshed weddings ',
       'Ideal by Design House',
       'Epic - Elevating Independence (formerly Independence of Portage County)',
       'Jetpack Shipping', 'Healing Strides Therapy and Wellness',
       'Richland Source', 'Docmann Marketing Group',
       'Cardinal Rental Sales ', 'Echo Valley Cookie Co.', 'KPG Creative',
       'iSynergy', 'Painesville City Local Schools ',
       'Kent Parks and Recreation', 'Houde Solutions ',
       'Centerline Biomedical', 'Kent Online', 'Media Source',
       'Kent State University Hockey Team', 'New Direction',
       'Kent State College of Nursing',
       'Community Foundation of Lorain County ', 'Union home mortgage ',
       'Deco-Crete ', 'Last Shop Film LLC', 'Kent State Univerity Museum',
       'ABM Industries ', 'Pittsburgh Pirates ', "Malley's Chocolates",
       'Fractal ', 'The Last Exit Books and Coffeehouse',
       'ARES Sportswear', 'Beaumont Scout Reservation',
       'Sinclair Media Group', 'Dead Talk Media LLC',
       'The Office of Global Education', 'Erie Apparel',
       'Parkside Peddlers', 'CorteX Racing', 'Mini Lessons Academy',
       'NXTGen Clean Energy Solutions',
       'Muskingum Watershed Conservancy District', 'Chaotic Goods',
       'Altamira', 'Sinclair media group ', 'Artsolute Media Group',
       'Eventys partners', 'Live Your Song', "L'OFFICIEL USA",
       'Epilepsy Association ', 'Digital Bloomz',
       'Freedom Hobby & Gaming', 'The Garnette Report', 'Color Beyond',
       'Alex Massey- At Your Service Memorial & ALS Charity Golf Outing (AMAYS)',
       'Portage County Board of Developmental Disabilities',
       'Market District',
       'St. Thomas Aquinas Highschool and Middle School',
       'Division of Student Life', 'Live Local MD Marketing',
       'JTM Products ', 'Kent State University School of Art',
       'Autism Speaks ',
       'KENT STATE COLLEGE OF ARCHITECTURE & ENVIRONMENTAL DESIGN',
       'Freedom Fellowship Savannah', 'School of Art',
       'Oasis Experiences', 'Perfect auto collection ', 'Planit Studios ',
       'WAOH TV ', 'A Special Wish ', 'Gazette Gal', 'TechHalo',
       'Akron Summit County Public Library, Mogadore Branch',
       'Community Action Akron Summit',
       'Counseling and Psychological Services at Kent State',
       'Kent State athletics ', 'WFMJ News', 'Innis Maggiore',
       'Cision/ PR Newswire', 'Miran',
       'Renegade Roofing and Design/The Simonelli Group',
       "Seasoned Brands - Aladdin's Eatery",
       'MODE: Motion Design Education Summit', 'KeenTechnic LLC',
       'Jumpstart Video ', 'Gold Horse Media', 'Flash Communications',
       'Catholic Education Through Media',
       'Kent State Division of Philanthropy and Alumni Engagement',
       'Main Street Barberton', 'We Are Foundation',
       'Louisville Public Library Makerspace',
       'Akron Summit County Public Library (Mogadore Branch)',
       'SCA International LLC',
       'Kent State University (College of Arts & Sciences Marketing Office)',
       'Safety and Community Care', 'True Digital Communications ',
       'Student Media- KSTV & Black Squirrel Entertainment ',
       'Cle Cotton Candy', 'CLE Cotton Candy',
       'Kent State College of the Arts Marketing Department',
       'The Fabric Pantry', 'Technova Industries', 'Games for love ',
       'Glauser School of Music',
       'Kent State University - Instructional Resource Center',
       'Cincinnati Insurance Companies', 'Believe in Dreams ',
       'Stark county family jobs and services ',
       'Reeves Fink and Knabb CO., LPA', 'Paramount Financial Planning',
       'Do Me Better Cards', 'Fashion Talks',
       "The Peaceful Warriors' Way", 'People Forward Network',
       "The Peaceful Warrior's Way", 'Jumpstart Video Production Company',
       'Leaf Home Bath', 'Puzzle Creative Solutions', 'Lancaster Safety',
       'JXB', 'DRB',
       'Rebecca Adele PR & Events / Avant-Garde Art & Craft Shows / C.L.E Cotton Candy',
       'Quiet Thoughts Matter', 'Diebold Nixdorf ', 'Trill Magazine',
       'Babcock & Wilcox ', 'Maggie’s Bridal and Prom',
       'Karl Road Baptist Church',
       'Big Brothers Big Sisters of Greater Cleveland', 'City of Parma',
       'Destination Cleveland', 'Henkel ', 'Caitlin Pope',
       'Gasser Chair Company', 'Playhouse Square ',
       'Cares Center at Kent State University ', 'Crash Cat Media Group',
       'A&J pest control', 'TH Custom', 'Vyrdia', 'Athena Project, Arts',
       'Ambassadors Football ', 'Jackpot Pictures', 'Fresh Twist',
       'Beyond Academy', 'Zillow', 'Cleveland Motorsports ',
       'D.A. International (Brand: Keitha)', 'Fleet Response ',
       "Matteo's", 'Kappa Sigma', 'United Way of Portage County',
       'KeyBank', '78th Street Studios', 'Fusion Magazine',
       'Heather B. Moore', 'Akron Community Studios', 'Impactasnap',
       'ohio employee ownership center', 'April G Photography',
       'Ohio Employee Owership Center', 'Simply Community',
       'Realty Assistant', 'Main Street Kent', 'Akron Soul Train',
       'WFMJ Youngstown News', 's', 'ECRM', 'Xctmedia ', 'Shurtape',
       'County Line Junk Removal ', 'dekstech', 'Help Labs',
       'Fashion Talks Foundation',
       'Kent State Student Recreation & Wellness Center',
       'McJak Candy Company LLC', 'Tokudaw', 'Marvin Content by Ashley',
       '898 Marketing', 'Faith United Methodist', 'Whalebone',
       "The Russell's Charm", 'MCA', 'Rental Reach', 'LuCha Beverage LLC',
       'Talking Solutions', 'LABOR Eyewear', 'On Point Dance Competition',
       'Chambers of Commerce Ravenna', 'Madison Square Garden Sports',
       'Jejune Magazine',
       'Kent State University and Universidade Católica Portuguesa',
       ' Chambers of Commerce ', 'Design Innovation',
       '2 Ticks and The Dog Productions', 'Shiftology Communication',
       'EnforcetheSport', '45press', 'War Horse Ink', 'Hot Literati',
       'Babcox Media', 'Route 8 Studios ', 'Maru Sports, Inc',
       'Faith Family Church', 'Scented Flame Candle Supply',
       'New Zoo and Adventure Park', 'Kent State University Libraries ',
       'Graphic Detail Incorporated ', 'RKNYC Jewelry',
       'Kent State Recreation and Wellness Center',
       'Crafting Immersive Stories in Lisbon', 'Three Train studios ',
       'Euclid Chemical Company', 'Vector Marketing',
       'Absolute Intense Wrestling', 'OneHope ',
       'Crown Fame Sports Media and Marketing', 'Graphic Detail, Inc.',
       'Portage Learning', 'Midwest Fastener Corp.', 'Route 8 Studio',
       'Cleveland Magazine ', 'Baker Hostetler Law', 'Workshop of Wishes',
       'The Portager', nan], dtype=object)

In [ ]:
intappdata = pd.DataFrame(intapp['Organization Name'])

intappdata.head(10)
#making a data frame for the company name

                                   Organization Name
0  KSU / CAPS - Counseling and Psychological serv...
1                                         Mail Pro 1
2                     Stow Munroe Falls City Schools
3                                         Kent Wired
4                 KENT STATE ATHLETIC COMMUNICATIONS
5       KSU/College of Communication and Information
6                                   Playhouse Square
7                           West County News Journal
8                              Christ Baptist Church
9                                              Fox 8

In [ ]:
intapp.groupby('Organization Name').count()['Submission Date']
#grouping by company name

Organization Name
 Chambers of Commerce                                         1
 Greater Cleveland Automobile Dealers’ Association (GCADA)    1
 In Step With Horses(ISWH) and American Tire Works(ATW)       1
10k Movement                                                  1
1895 Films                                                    4
                                                             ..
martinwolf                                                    1
ohio employee ownership center                                1
peaches and cream                                             1
red point digital                                             1
s                                                             1
Name: Submission Date, Length: 664, dtype: int64

In [ ]:
intapp.groupby('Organization Zip').count()['Submission Date'].sort_values(ascending = False)[0:20]
#grouping by zip code

Organization Zip
44240    90
44242    87
44304    26
44224    23
44115    22
44313    17
44308    17
44114    17
44139    14
44720    14
44311    13
44243    13
44145    13
44125    12
44266    12
44236    12
44087     9
44107     9
44131     8
44095     7
Name: Submission Date, dtype: int64

In [ ]:
intappdata = pd.DataFrame(intapp['Internship Job Title'])

intappdata.head(20)
#making a data frame from job title

                                 Internship Job Title
0                      Social media/marketing intern
1                                           Designer
2                             Public Relations Intern
3                                Designer/Illustrator
4                       Athletic Communication Intern
5                                    Student Interns
6                               Graphic Design Intern
7                                         News Intern
8                                        Web Designer
9                       Friday Night Touchdown Intern
10           Video Production and Audio Mixing Intern
11                                 Compliance Intern
12                    Media and Technology DCS Intern
13                              Graphic Design Intern
14                   Editorial and Photography intern
15                                Video Editor Intern
16  WJW-TV FOX 8 ‘Friday Night Touchdown’ Sports I...
17                            Public Relations Intern
18                     Promotion/Social Media Manager
19                      Penguins Radio Network Intern

In [17]:
intapp['Internship Job Title'].head(10)

0    Social media/marketing intern
1                         Designer
2           Public Relations Intern
3              Designer/Illustrator
4     Athletic Communication Intern
5                  Student Interns
6             Graphic Design Intern
7                       News Intern
8                      Web Designer
9     Friday Night Touchdown Intern
Name: Internship Job Title, dtype: object

In [ ]:
intappdata = pd.DataFrame(intapp['CCI Major'])

intappdata.head(10)
#making a data frame form major

                                 CCI Major
0                    Communication Studies
1  Visual Communication Design (BFA or BA)
2                    Communication Studies
3  Visual Communication Design (BFA or BA)
4                    Communication Studies
5                    Communication Studies
6  Visual Communication Design (BFA or BA)
7                               Journalism
8            Emerging Media and Technology
9                    Communication Studies

In [ ]:
intappdata = pd.DataFrame(intapp['Organization State'])

intappdata.head(10)
#data frame for state

  Organization State
0               Ohio
1               Ohio
2               Ohio
3               Ohio
4               Ohio
5               Ohio
6               Ohio
7       Pennsylvania
8               Ohio
9               Ohio

In [ ]:
intapp.groupby('Organization State').count()['Submission Date'].sort_values(ascending = False)[0:60]
#grouping by state

Organization State
Ohio               739
California          32
New York            31
International       25
Pennsylvania        23
Massachusetts       11
Virginia             9
Wisconsin            7
Colorado             6
Florida              6
Georgia              6
Washington           6
Texas                6
Connecticut          5
Indiana              5
New Jersey           4
Arizona              3
Missouri             3
Michigan             3
Nevada               2
Maryland             2
Kentucky             2
Illinois             2
Washington D.C.      2
North Carolina       1
Maine                1
Oklahoma             1
Louisiana            1
Tennessee            1
Idaho                1
Name: Submission Date, dtype: int64

In [ ]:
intapp.groupby('Internship Job Title').count()['Submission Date'].sort_values(ascending = False)[0:10]
#grouping by job title

Internship Job Title
Graphic Design Intern      44
Intern                     31
Graphic Designer           28
Marketing Intern           25
Social Media Intern        13
Communications Intern      12
Video Production Intern    11
Video Editor               11
Public Relations Intern    11
Photographer               10
Name: Submission Date, dtype: int64

In [ ]:
intappdata = pd.DataFrame(intapp['Semester Student Registered'])

intappdata.head(10)
#making a data frame for semester

  Semester Student Registered
0                   Fall 2023
1                 Summer 2023
2                   Fall 2023
3                   Fall 2023
4                   Fall 2023
5                   Fall 2023
6                 Summer 2023
7                   Fall 2023
8                   Fall 2023
9                         NaN

In [ ]:
intapp.groupby('Semester Student Registered').count()['Submission Date'].sort_values(ascending = False)
#gropu by the number of students per semester

Semester Student Registered
Summer 2024    159
Summer 2025    137
Spring 2026     93
Spring 2024     89
Fall 2025       77
Spring 2025     69
Fall 2024       67
Fall 2023       62
Summer 2026     49
Fall 2026       13
Summer 2023      3
Name: Submission Date, dtype: int64

In [24]:
semester_counts = intapp.groupby('Semester Student Registered').size().sort_index()
#I think Professor Silva helped me with this during office hours

In [ ]:
fig = px.bar(x=semester_counts.index,y=semester_counts.values,labels={'x': 'Semester', 'y': 'Number of Students'},
    title='Students in Internships per Semester')

fig.show()
#looked at plotly group 1's first bar graph for this part

In [ ]:
intapp.groupby('CCI Major').count()['Submission Date'].sort_values(ascending = False)

#replicated from above to group according to major to ultimately make a pie chart for this one

CCI Major
Visual Communication Design (BFA or BA)    256
Digital Media Production                   213
Journalism                                 120
Public Relations                            97
Communication Studies                       89
Emerging Media and Technology               72
Advertising                                 69
Photography                                 29
User Experience Design                       1
Name: Submission Date, dtype: int64

In [ ]:
major_counts = intapp.groupby('CCI Major').size().sort_values(ascending=False)

#just going to copy what I did above

In [ ]:
fig2 = go.Figure(data=[go.Pie(labels=major_counts.index,values=major_counts.values,title="CCI Major Distribution")])

fig2.show()
#found this in plotlygroup2's first pie chart and copied it over, now I'm cooking

In [29]:
intapp.groupby('Organization State').count()['Submission Date'].sort_values(ascending = False)[0:60]

Organization State
Ohio               739
California          32
New York            31
International       25
Pennsylvania        23
Massachusetts       11
Virginia             9
Wisconsin            7
Colorado             6
Florida              6
Georgia              6
Washington           6
Texas                6
Connecticut          5
Indiana              5
New Jersey           4
Arizona              3
Missouri             3
Michigan             3
Nevada               2
Maryland             2
Kentucky             2
Illinois             2
Washington D.C.      2
North Carolina       1
Maine                1
Oklahoma             1
Louisiana            1
Tennessee            1
Idaho                1
Name: Submission Date, dtype: int64

In [30]:
state_counts = intapp.groupby('Organization State').size().dropna()
state_counts = state_counts.head(20)
#again copied from above but I only want the top 20

In [31]:
#asked chatgpt: "Is there a formula to make a heat map in python with plotly" and I filled in the blanks since this is way above my skill level

fig3 = go.Figure(data=go.Choropleth(
    locations=state_counts.index,   
    z=state_counts.values,         
    locationmode='USA-states',      
    colorscale='Blues',
    colorbar_title="Submissions"
))

fig3.update_layout(
    title_text='Internship Submissions by State',
    geo_scope='usa'  # limits map to U.S.

)
fig3.update_layout(
    title='Internships by State',
    geo=dict(
        lakecolor='rgb(255, 255, 255)'
    ))
fig3.show()

In [32]:
#I learned that it's blank because plotly only recognizes state abreviations for maps, and 
# my spreadsheet has full state names so I pulled this from chatgpt to clean it up
us_state_abbrev = {
    'Alabama': 'AL','Alaska': 'AK','Arizona': 'AZ','Arkansas': 'AR',
    'California': 'CA','Colorado': 'CO','Connecticut': 'CT','Delaware': 'DE',
    'Florida': 'FL','Georgia': 'GA','Hawaii': 'HI','Idaho': 'ID',
    'Illinois': 'IL','Indiana': 'IN','Iowa': 'IA','Kansas': 'KS',
    'Kentucky': 'KY','Louisiana': 'LA','Maine': 'ME','Maryland': 'MD',
    'Massachusetts': 'MA','Michigan': 'MI','Minnesota': 'MN',
    'Mississippi': 'MS','Missouri': 'MO','Montana': 'MT',
    'Nebraska': 'NE','Nevada': 'NV','New Hampshire': 'NH',
    'New Jersey': 'NJ','New Mexico': 'NM','New York': 'NY',
    'North Carolina': 'NC','North Dakota': 'ND','Ohio': 'OH',
    'Oklahoma': 'OK','Oregon': 'OR','Pennsylvania': 'PA',
    'Rhode Island': 'RI','South Carolina': 'SC','South Dakota': 'SD',
    'Tennessee': 'TN','Texas': 'TX','Utah': 'UT','Vermont': 'VT',
    'Virginia': 'VA','Washington': 'WA','West Virginia': 'WV',
    'Wisconsin': 'WI','Wyoming': 'WY'
}

# clean + convert
intapp['Organization State'] = intapp['Organization State'].str.strip()
intapp['State Abbrev'] = intapp['Organization State'].map(us_state_abbrev)

In [33]:
state_counts = intapp.groupby('State Abbrev').size().dropna()

In [34]:
fig3 = go.Figure(data=go.Choropleth(
    locations=state_counts.index,   
    z=state_counts.values,          
    locationmode='USA-states',      
    colorscale='Blues',
    colorbar_title="Submissions"
))

fig3.update_layout(
    title_text='Internship Submissions by State',
    geo_scope='usa'  # limits map to U.S.

)
fig3.update_layout(
    title='Internships by State',
    geo=dict(
        lakecolor='rgb(255, 255, 255)'
    ))
fig3.show()

In [35]:
#not sure how to make this better. maybe expanding just the ohio and showing 
# where in ohio they are going would be of interest to econ dev groups. what would be interesting prospective families? current students? waht if I
#exclude ohio to make it less broad (1-32 outside of ohio)
#still need to figure out how to clean up that spreadsheet with company names too

In [36]:
intapp.groupby('Organization Zip').count()['Submission Date'].sort_values(ascending = False)[0:20]

Organization Zip
44240    90
44242    87
44304    26
44224    23
44115    22
44313    17
44308    17
44114    17
44139    14
44720    14
44311    13
44243    13
44145    13
44125    12
44266    12
44236    12
44087     9
44107     9
44131     8
44095     7
Name: Submission Date, dtype: int64

In [37]:
#professor silva reminded me how to do this in class
ohio_data = intapp[intapp['Organization State'] == 'Ohio']

In [38]:
#asked chatgpt how to zoom into ohio further, I had to install pgeocode at my terminal and import it 

nomi = pgeocode.Nominatim('us')

# I guess this makes the zip codes a string
intapp['Organization Zip'] = intapp['Organization Zip'].astype(str).str[:5]

# this gets the lat/lon so glad my professor had mercy on my soul and let me switch to this project
intapp['lat'] = intapp['Organization Zip'].apply(lambda x: nomi.query_postal_code(x).latitude)
intapp['lon'] = intapp['Organization Zip'].apply(lambda x: nomi.query_postal_code(x).longitude)

In [ ]:
ohio_data = intapp[intapp['Organization State'] == 'Ohio']
#getting ohio only

In [ ]:
zip_counts = ohio_data.groupby(['Organization Zip', 'lat', 'lon']).size().reset_index(name='count')
#grouping by zip codes

In [41]:
#I don't love this, not useful. I am just not sure it's useful to anyone

fig4 = px.scatter_geo(
    zip_counts,
    lat='lat',
    lon='lon',
    size='count',
    hover_name='Organization Zip',
    scope='usa'
)

fig4.update_layout(
    title='Internship Locations in Ohio (by ZIP Code)',
    geo=dict(
        center={'lat': 40.4173, 'lon': -82.9071},  # center of Ohio
        projection_scale=6  # zoom into Ohio
    )
)

fig4.show()

In [54]:
#I'm thinking taking ohio out would help to better emphasize the numbers in other states

state_counts_no_oh = state_counts[state_counts.index != 'OH']

In [ ]:
#just copied this over from the link David sent to me without really looking at it, clearly I need to work on it
us_cities = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/us-cities-top-1k.csv")

fig = px.scatter_map(us_cities, lat="lat", lon="lon", hover_name="City", hover_data=["State", "Population"],
                        color_discrete_sequence=["fuchsia"], zoom=3, height=300)
fig.update_layout(map_style="open-street-map")
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [55]:
state_counts_no_oh

State Abbrev
AZ     3
CA    32
CO     6
CT     5
FL     6
GA     6
ID     1
IL     2
IN     5
KY     2
LA     1
MA    11
MD     2
ME     1
MI     3
MO     3
NC     1
NJ     4
NV     2
NY    31
OK     1
PA    23
TN     1
TX     6
VA     9
WA     6
WI     7
dtype: int64

In [56]:
fig3 = go.Figure(data=go.Choropleth(
    locations=state_counts_no_oh.index,   # state abbreviat
    z=state_counts_no_oh.values,          # counts
    locationmode='USA-states',      
    colorscale='Blues',
    colorbar_title="Submissions"
))

fig3.update_layout(
    title_text='Internship Submissions by State',
    geo_scope='usa'  # limits map to U.S.

)
fig3.update_layout(
    title='Internships by State',
    geo=dict(
        lakecolor='rgb(255, 255, 255)'
    ))
fig3.show()

In [ ]:
state_counts_no_oh = state_counts[state_counts.index != 'Oh'] 
#i am trying to take ohio out to emphasize where most of these internshps are

How does dash work