In [1]:
import plotly.express as px
import plotly as pl
import pandas as pd

In [2]:
food  = pd.read_csv('daily_food_delivery_orders.csv')
food

,order_id,order_date,customer_age,restaurant_type,order_value,delivery_distance_km,delivery_time_minutes,payment_method,delivery_partner_rating,order_status
0,1,2024-11-05,62,Indian,497.51,11.07,79,UPI,3.9,Cancelled
1,2,2024-08-20,35,Bakery,232.32,5.83,69,Wallet,2.7,Cancelled
2,3,2024-02-28,34,Italian,540.82,3.61,70,Wallet,3.4,Cancelled
3,4,2024-05-26,65,Cafe,1197.99,3.66,18,Card,4.6,Cancelled
4,5,2024-09-21,40,Indian,947.03,12.08,57,UPI,4.9,Delayed
...,...,...,...,...,...,...,...,...,...,...
2595,2596,2024-05-20,46,Cafe,738.51,9.12,31,Wallet,4.5,Cancelled
2596,2597,2024-05-15,56,Indian,421.78,8.29,66,Card,2.8,Delayed
2597,2598,2024-10-18,32,Cafe,1009.93,12.80,73,UPI,4.4,Delivered
2598,2599,2024-04-24,55,Bakery,240.97,13.56,56,Cash,4.3,Delivered
2599,2600,2024-01-10,58,Bakery,510.56,2.30,49,Cash,4.2,Delivered

In [3]:
status_counts=food["restaurant_type"].value_counts().reset_index()
status_counts.columns = ["restaurant_type", "frequency"] 

fig1 = px.bar(status_counts, x= "restaurant_type", y= "frequency", title="Frequency of Restaurant Type", labels={"restaurant_type": "Restaurant Type", "frequency": "Count"},
text = "frequency",
color = "restaurant_type",
color_discrete_sequence=["brown", "#D38B5D", "red", "yellow", "green", "orange"])
fig1.show()

In [4]:
food20=food.head (20)
food20

,order_id,order_date,customer_age,restaurant_type,order_value,delivery_distance_km,delivery_time_minutes,payment_method,delivery_partner_rating,order_status
0,1,2024-11-05,62,Indian,497.51,11.07,79,UPI,3.9,Cancelled
1,2,2024-08-20,35,Bakery,232.32,5.83,69,Wallet,2.7,Cancelled
2,3,2024-02-28,34,Italian,540.82,3.61,70,Wallet,3.4,Cancelled
3,4,2024-05-26,65,Cafe,1197.99,3.66,18,Card,4.6,Cancelled
4,5,2024-09-21,40,Indian,947.03,12.08,57,UPI,4.9,Delayed
5,6,2024-03-16,51,Italian,835.75,3.56,85,UPI,3.8,Delayed
6,7,2024-11-20,52,Cafe,771.83,14.37,80,Card,3.7,Delivered
7,8,2024-11-24,52,Chinese,926.20,12.81,19,UPI,4.4,Delayed
8,9,2024-07-23,38,Bakery,548.11,13.54,42,Cash,4.1,Delayed
9,10,2024-07-01,24,Fast Food,177.18,8.15,29,Cash,2.9,Delivered
10,11,2024-09-16,27,Cafe,806.68,5.43,53,Cash,3.1,Cancelled
11,12,2024-08-27,61,Bakery,1193.33,9.68,26,UPI,3.5,Delivered
12,13,2024-01-09,31,Chinese,758.14,1.28,57,Cash,2.9,Delayed
13,14,2024-09-02,47,Cafe,937.07,13.41,88,Wallet,3.8,Cancelled
14,15,2024-08-21,62,Chinese,810.18,12.36,87,Cash,5.0,Delayed
15,16,2024-07-24,38,Bakery,773.12,9.07,50,Wallet,2.8,Cancelled
16,17,2024-04-09,54,Cafe,816.14,10.95,86,UPI,4.8,Delayed
17,18,2024-04-20,43,Cafe,640.60,4.49,50,Cash,4.1,Delayed
18,19,2024-03-01,54,Indian,193.87,4.40,63,UPI,2.8,Delivered
19,20,2024-08-23,23,Chinese,183.09,14.11,52,Cash,2.9,Cancelled

In [5]:
fig2 = px.line(food20, x="order_date", y="order_value", markers=True)
fig2.show()

In [6]:
food20['in_order_dates']=pd.to_datetime(food['order_date'])
food20.sort_values('in_order_dates', inplace=True)
food20

/var/folders/tg/tyhvgh7x3_zfjmpm7y0nqq8c0000gp/T/ipykernel_4580/765956221.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/tg/tyhvgh7x3_zfjmpm7y0nqq8c0000gp/T/ipykernel_4580/765956221.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,order_id,order_date,customer_age,restaurant_type,order_value,delivery_distance_km,delivery_time_minutes,payment_method,delivery_partner_rating,order_status,in_order_dates
12,13,2024-01-09,31,Chinese,758.14,1.28,57,Cash,2.9,Delayed,2024-01-09
2,3,2024-02-28,34,Italian,540.82,3.61,70,Wallet,3.4,Cancelled,2024-02-28
18,19,2024-03-01,54,Indian,193.87,4.40,63,UPI,2.8,Delivered,2024-03-01
5,6,2024-03-16,51,Italian,835.75,3.56,85,UPI,3.8,Delayed,2024-03-16
16,17,2024-04-09,54,Cafe,816.14,10.95,86,UPI,4.8,Delayed,2024-04-09
17,18,2024-04-20,43,Cafe,640.60,4.49,50,Cash,4.1,Delayed,2024-04-20
3,4,2024-05-26,65,Cafe,1197.99,3.66,18,Card,4.6,Cancelled,2024-05-26
9,10,2024-07-01,24,Fast Food,177.18,8.15,29,Cash,2.9,Delivered,2024-07-01
8,9,2024-07-23,38,Bakery,548.11,13.54,42,Cash,4.1,Delayed,2024-07-23
15,16,2024-07-24,38,Bakery,773.12,9.07,50,Wallet,2.8,Cancelled,2024-07-24
1,2,2024-08-20,35,Bakery,232.32,5.83,69,Wallet,2.7,Cancelled,2024-08-20
14,15,2024-08-21,62,Chinese,810.18,12.36,87,Cash,5.0,Delayed,2024-08-21
19,20,2024-08-23,23,Chinese,183.09,14.11,52,Cash,2.9,Cancelled,2024-08-23
11,12,2024-08-27,61,Bakery,1193.33,9.68,26,UPI,3.5,Delivered,2024-08-27
13,14,2024-09-02,47,Cafe,937.07,13.41,88,Wallet,3.8,Cancelled,2024-09-02
10,11,2024-09-16,27,Cafe,806.68,5.43,53,Cash,3.1,Cancelled,2024-09-16
4,5,2024-09-21,40,Indian,947.03,12.08,57,UPI,4.9,Delayed,2024-09-21
0,1,2024-11-05,62,Indian,497.51,11.07,79,UPI,3.9,Cancelled,2024-11-05
6,7,2024-11-20,52,Cafe,771.83,14.37,80,Card,3.7,Delivered,2024-11-20
7,8,2024-11-24,52,Chinese,926.20,12.81,19,UPI,4.4,Delayed,2024-11-24

In [7]:
fig3 = px.line(food20, x="in_order_dates", y="order_value", markers=True,
   labels=dict(in_order_dates="Order Dates", order_value="Order Value") )
fig3.update_traces(marker=dict(color="Green", size=10, symbol="square"), 
                   line=dict(width=3, color="red"))
fig3.show()

In [8]:
fig4=px.scatter(
    food,
    x="delivery_distance_km",
    y="delivery_time_minutes"
)
fig4.show()

In [9]:
fig4=px.scatter(
    food,
    x="delivery_distance_km",
    y="delivery_time_minutes",
    color = "delivery_partner_rating",
)
fig4.show()

In [10]:
fig4=px.scatter(
    food,
    x="delivery_distance_km",
    y="delivery_time_minutes",
    color = "delivery_partner_rating",
    symbol = "order_status",
)
fig4.show()

In [11]:
foodSample=food.sample(n=50)
foodSample.head()
#.sample is a pandas funchtion that takes a random sample

,order_id,order_date,customer_age,restaurant_type,order_value,delivery_distance_km,delivery_time_minutes,payment_method,delivery_partner_rating,order_status
959,960,2024-07-29,56,Chinese,673.35,7.23,79,Wallet,3.1,Cancelled
333,334,2024-06-26,44,Chinese,269.71,8.62,85,Cash,4.6,Delayed
1908,1909,2024-03-10,56,Italian,480.42,14.57,15,UPI,3.0,Cancelled
310,311,2024-01-08,63,Chinese,361.86,14.43,29,UPI,3.2,Delivered
1069,1070,2024-07-30,57,Indian,485.80,3.66,45,Card,3.7,Cancelled

In [12]:
fig5=px.scatter(
    foodSample,
    x="delivery_distance_km",
    y="delivery_time_minutes",
    color = "delivery_partner_rating",
    symbol = "order_status",
)
fig5.show()

In [13]:
fig5=px.scatter(
    foodSample,
    x="delivery_distance_km",
    y="delivery_time_minutes",
    color = "delivery_partner_rating",
    symbol = "order_status",
)
fig5.update_traces(marker=dict (size = 20, opacity = 0.5, line = dict (width =2, color ="black")))
fig5.show()

In [14]:
fig5=px.scatter(
    foodSample,
    x="delivery_distance_km",
    y="delivery_time_minutes",
    color = "delivery_partner_rating",
    symbol = "order_status",
)
fig5.update_traces(marker=dict (size = 20, opacity = 0.5, line = dict (width =2, color ="black")))
fig5.update_layout(legend = {"yanchor": "top", "y": 0.88, "xanchor" : "left", "x" : 1.13})
#this allows us to see the legend with x and y anchors not pixel counts but %, 
fig5.show()

In [15]:
fig5=px.scatter(
    foodSample,
    x="delivery_distance_km",
    y="delivery_time_minutes",
    color = "delivery_partner_rating",
    symbol = "order_status",
)
fig5.update_traces(marker=dict (size = 20, opacity = 0.5, line = dict (width =2, color ="black")))
fig5.update_layout(legend = {"yanchor": "top", "y": 0.88, "xanchor" : "left", "x" : 1.13})
#this allows us to see the legend with x and y anchors not pixel counts but %, 
fig5.show()

In [18]:
fig5=px.scatter(
    foodSample,
    x="delivery_distance_km",
    y="delivery_time_minutes",
    color = "delivery_partner_rating",
    symbol = "order_status",
    title = "Delivery Distance vs. Delivery Time",
    labels = {"delivery_distance_km": "Delivery Distance (km)", "delivery_time_minutes" : "Delivery Time (min)", "delivery_partner_rating": "Delivery Partner Rating", "order_status": "Order Status"}
)
fig5.update_traces(marker=dict (size = 20, opacity = 0.5, line = dict (width =2, color ="black")))
fig5.update_layout(legend = {"yanchor": "top", "y": 0.88, "xanchor" : "left", "x" : 1.13})
#this allows us to see the legend with x and y anchors not pixel counts but %, 
fig5.show()

In [29]:
PLOT_TEMPLATE = "plotly_white"

status_color ={
    "Delivered":"#2A9D8F",
    "Delayed": "#E9C46A",
    "Cancelled": "#E63946"

}
food["age_group"]=pd.cut(
food["customer_age"],
bins=[0, 18, 25, 35, 45, 60, 100],
labels = ["<18", "18-25", "26-35", "36-45", "46-60", "60+"]

)

In [30]:
fig7 = px.histogram(
    food,
    x="order_value",
    color = "order_status",
    color_discrete_map =status_color,
    facet_col = "age_group",
    facet_col_wrap=3,
    nbins = 30,
    title = "Order Value Distribution by Age Group and Status",
    labels = {"order_value": "Order Value"}

)
fig7.update_layout(template=PLOT_TEMPLATE)
fig7.show()