# Kristin
## Now that we have learned about Plotly express which allows us to automatically build figures, now we are going to learn about graph objects which allows us to modify and go beyond static figures. 

## We use graph objects when we want to build things like chart templates, multiple traces, and interactive dashboards just to name a few.

-Chart templates: chart templates are predefined style settings that control the appearance of a figure—things like colors, fonts, background, gridlines, and default formatting.

-Multiple traces: adding more than one dataset (or graphical layer) to the same figure. Each trace represents a single set of data with a specific visualization type (line, bar, scatter, etc.).


## Okay everyone! We're going to get started like we always do in Terminal or Command Shell
conda activate indata26 (whatever it is called)
### Here we're going to install plotly graph objects:
# conda install -c conda-forge plotly 
then ls for Mac dir for Windows to check it is installed

cd indata26 (whatever it is called)

code .

# you should have downloaded the pokedex file and you can drag it over to vscode if you have not already done soe

In [1]:
import plotly.graph_objects as go # or plotly.express as px
from plotly.subplots import make_subplots
import json
import pandas as pd
import numpy as np
#Kristin
#start by installing plotly graph objects as go 
#install plotly subplots by typing from ploty sublplosts import make subplots
#import json
#import pandas as pd
#and import numpy as np

In [2]:
with open('pokedex.json') as p:
    pokedex = json.load(p)
#Kristin
#next we want to open our pokemon file and convert it to an object

# Cadie start

In [3]:
type(pokedex)
#Cadie start
#we want to know what type of object this is so we enter type

dict

In [4]:
pokedex.keys()
#Cadie
#in order to find out what the

dict_keys(['pokemon'])

In [5]:
type(pokedex['pokemon'])
#Cadie
#to find out how many are in the list

list

In [6]:
len(pokedex['pokemon'])
#Cadie
#to find out how many items are in the list, we enter

151

In [7]:
pokedex['pokemon'][0]
#Cadie
#Perfect! our hunch was right, this is the data for Bulbasaur
#we want to explore this data further and find out all the field names (keys) for the first Pokémon in the dataset.

{'id': 1,
 'num': '001',
 'name': 'Bulbasaur',
 'img': 'http://www.serebii.net/pokemongo/pokemon/001.png',
 'type': ['Grass', 'Poison'],
 'height': '0.71 m',
 'weight': '6.9 kg',
 'candy': 'Bulbasaur Candy',
 'candy_count': 25,
 'egg': '2 km',
 'spawn_chance': 0.69,
 'avg_spawns': 69,
 'spawn_time': '20:00',
 'multipliers': [1.58],
 'weaknesses': ['Fire', 'Ice', 'Flying', 'Psychic'],
 'next_evolution': [{'num': '002', 'name': 'Ivysaur'},
  {'num': '003', 'name': 'Venusaur'}]}

In [8]:
pokedex['pokemon'][0].keys()
#Cadie
#we can see there's many things to graph: type, height, weight, if there's a pre/next evolution, weaknesses

dict_keys(['id', 'num', 'name', 'img', 'type', 'height', 'weight', 'candy', 'candy_count', 'egg', 'spawn_chance', 'avg_spawns', 'spawn_time', 'multipliers', 'weaknesses', 'next_evolution'])

In [9]:

pokedata = pd.DataFrame(pokedex['pokemon'])
#Cadie
#now that we know there's only one key, a list of dictionaries, let's make a dataframe out ok the 'pokemon' list
#don't forget that data frame is case sensitive
pokedata.head(10)

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
5,6,006,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"[Fire, Flying]",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,None,"[Water, Electric, Rock]",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':..."
6,7,007,Squirtle,http://www.serebii.net/pokemongo/pokemon/007.png,[Water],0.51 m,9.0 kg,Squirtle Candy,25.0,2 km,0.5800,58.00,04:25,[2.1],"[Electric, Grass]","[{'num': '008', 'name': 'Wartortle'}, {'num': ...",NaN
7,8,008,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,[Water],0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.0340,3.40,07:02,[1.4],"[Electric, Grass]","[{'num': '009', 'name': 'Blastoise'}]","[{'num': '007', 'name': 'Squirtle'}]"
8,9,009,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,[Water],1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,00:06,None,"[Electric, Grass]",NaN,"[{'num': '007', 'name': 'Squirtle'}, {'num': '..."
9,10,010,Caterpie,http://www.serebii.net/pokemongo/pokemon/010.png,[Bug],0.30 m,2.9 kg,Caterpie Candy,12.0,2 km,3.0320,303.20,16:35,[1.05],"[Fire, Flying, Rock]","[{'num': '011', 'name': 'Metapod'}, {'num': '0...",NaN

# Our DataFrame exists! :D

## What's one of the most obvious ways to categorize Pokemon into a few groups? (Types)

Well, that's an issue right now, if you look at the type column can anyone see why? (It's a list)

Right, so we're going to need to break these lists into their own columns, luckily using pandas there's already a function we know and love to do this quite easily: dataframe!

Because we want a 2 dimensional teble of data, we can take the current "type" column and break it into a mini dataframe using this syntax:

In [10]:
pokedata[['type1','type2']] = pd.DataFrame(pokedata.type.tolist(), index= pokedata.index)
pokedata.head(10)
#Cadie

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None
5,6,006,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"[Fire, Flying]",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,None,"[Water, Electric, Rock]",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':...",Fire,Flying
6,7,007,Squirtle,http://www.serebii.net/pokemongo/pokemon/007.png,[Water],0.51 m,9.0 kg,Squirtle Candy,25.0,2 km,0.5800,58.00,04:25,[2.1],"[Electric, Grass]","[{'num': '008', 'name': 'Wartortle'}, {'num': ...",NaN,Water,None
7,8,008,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,[Water],0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.0340,3.40,07:02,[1.4],"[Electric, Grass]","[{'num': '009', 'name': 'Blastoise'}]","[{'num': '007', 'name': 'Squirtle'}]",Water,None
8,9,009,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,[Water],1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,00:06,None,"[Electric, Grass]",NaN,"[{'num': '007', 'name': 'Squirtle'}, {'num': '...",Water,None
9,10,010,Caterpie,http://www.serebii.net/pokemongo/pokemon/010.png,[Bug],0.30 m,2.9 kg,Caterpie Candy,12.0,2 km,3.0320,303.20,16:35,[1.05],"[Fire, Flying, Rock]","[{'num': '011', 'name': 'Metapod'}, {'num': '0...",NaN,Bug,None

In [38]:
typegroup = pokedata.groupby('type1').count()['id']
typegroup
#Cadie
#lets create a separate grouping for main types, then lets get the pokecolors_map from Canvas

type1
Bug         12
Dragon       3
Electric     9
Fighting     7
Fire        12
Ghost        3
Grass       12
Ground       8
Ice          2
Normal      24
Poison      14
Psychic      8
Rock         9
Water       28
Name: id, dtype: int64

In [39]:
fig1 = go.Figure(data=[go.Bar(x=typegroup.index, y=typegroup.values)])

fig1.show()
#Cadie end

In [ ]:
pokecolors_map = {
	'Normal': '#A8A77A',
	'Fire': '#EE8130',
	'Water': '#6390F0',
	'Electric': '#F7D02C',
	'Grass': '#7AC74C',
	'Ice': '#96D9D6',
	'Fighting': '#C22E28',
	'Poison': '#A33EA1',
	'Ground': '#E2BF65',
	'Flying': '#A98FF3',
	'Psychic': '#F95587',
	'Bug': '#A6B91A',
	'Rock': '#B6A136',
	'Ghost': '#735797',
	'Dragon': '#6F35FC',
	'Dark': '#705746',
	'Steel': '#B7B7CE',
	'Fairy': '#D685AD',
}
# so, for some plotly visualizations, you can use the "color_discrete_map" selector to do exactly what we're manually doing here.
	# ((( Elle couldn't figure it out okay DX but the logic stays the same)))
# Then, for the color selector, you give a list of in this case, pokemon type names (typegroup.index)
pokecolors = typegroup.index.map(pokecolors_map)
pokecolors= list(pokecolors)
# With a dictionary (above) and a 1:1 correlation between name and color, the colors are then mapped accordingly!
#Magic :D
pokecolors
#Cadie
#now we have types categorized we can make our first simple visualization: a bar graph!

['#A6B91A',
 '#6F35FC',
 '#F7D02C',
 '#C22E28',
 '#EE8130',
 '#735797',
 '#7AC74C',
 '#E2BF65',
 '#96D9D6',
 '#A8A77A',
 '#A33EA1',
 '#F95587',
 '#B6A136',
 '#6390F0']

# Donald start

Okay! Now we're going to update that original bar chart to be mapped to the colors. You can copy and paste the same chart as before but we're going to edit the name to be fig1 and after y=typegroup.values, we're going to add marker_color=pokecolors

In [14]:
fig1 = go.Figure(data=[go.Bar(x=typegroup.index, y=typegroup.values,
 marker_color=pokecolors)])
#Donald
fig1.show()

#how cool! but we can make this graph a bit more helpful by making it a pie chart, 
# so we can see what percentage of the whole each group makes up 
# the syntax is a bit different so we're going to type this one out

In [15]:
fig2 = go.Figure(
    data=[
    go.Pie(
        labels=typegroup.index, 
        values=typegroup.values,
        marker=dict(colors=pokecolors),
        title="Gen 1 Pokemon by Main Type"
        )])

fig2.show()
#Donald
#This is a pretty cool chart, it makes me want to see a pie chart of the evolution stages, let's look at our dataframe again

In [16]:
pokedata.tail()
#donald
#okay so we can see here that there is no evolution column, but there are previous and next evolution columns, 
# which either have lists or nulls, 
# lets see what datatype null is so we can figure out the easoest way to sort these

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,Dragon,None
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",Dragon,None
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",Dragon,Flying
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None

In [17]:
type(pokedata['next_evolution'][150])

#okay, so now we know that a null is a float, that makes the rest really easy

float

# Elle on the board draws a quick chart

There are 4 pokemon evolution stages: Starter Middle Final and Lone

Starter has next evolutions but no prev

Middle has both next and prev

Final has prev but no next

Lone has no prev no next

### So using numpy select we can make:

In [18]:
conditions = [
    (pokedata['next_evolution'].apply(isinstance, args=(list,))) & (pokedata['prev_evolution'].apply(isinstance, args=(float,))),
    (pokedata['next_evolution'].apply(isinstance, args=(float,))) & (pokedata['prev_evolution'].apply(isinstance, args=(list,))),
    (pokedata['next_evolution'].apply(isinstance, args=(float,))) & (pokedata['prev_evolution'].apply(isinstance, args=(float,)))
]

choices = ["Starter", "Final", "Lone"]
pokedata['evolution_stage'] = np.select(conditions, choices, default="Middle")
#Donald
#Apply conditions; default to "Middle" if none are met

In [19]:
#let's check our work!
pokedata.tail()
#perfect let's make a quick group so we can add an evolution visualization to our plot

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,Dragon,None,Starter
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",Dragon,None,Middle
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",Dragon,Flying,Final
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None,Lone
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None,Lone

In [20]:
evol = pokedata.groupby('evolution_stage').count()['id']
evol
#Donald

evolution_stage
Final      56
Lone       25
Middle     16
Starter    54
Name: id, dtype: int64

In [21]:
fig3 = make_subplots(rows = 1, cols = 2, specs=[[{'type':'domain'}, {'type':'domain'}]])
#using make_subplots here
fig3.add_trace(
    go.Pie(
        labels=typegroup.index, 
        values=typegroup.values,
        marker=dict(colors=pokecolors),
        title="Gen 1 Pokemon by Main Type"
        ),
        1, 1)
# you can copy and paste this from the other chart
fig3.add_trace(
    go.Pie(
        labels=evol.index, 
        values=evol.values,
        title="Gen 1 Pokemon by Evolution Stage"
        ),
        1, 2)

fig3.show()
#Donald stop

# Elle

### Okay so I don't know about you but these graphs are WAY too simple fo my taste! let's turn it up a notch!

We're going to move onto scatterplots, and I think I want to see which Pokemon is the biggest! Let's look at our dataframe's columns again

In [22]:
pokedata.head(1)
#I only need to see the column names
# oh great, we can make a scatterplot with weight and height
#Idk about you but those weight and height values look... fishy let's check em out

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.69,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,Starter

In [23]:
type(pokedata['weight'][0])

str

In [24]:
type(pokedata['height'][0])
#I knew it!! We're going to have to turn these into continuous in order to get them to work

str

In [25]:
pokedata['weight_kg'] = pokedata['weight'].str.replace(' kg', '', regex=False)
pokedata['weight_kg'] = pd.to_numeric(pokedata['weight_kg'])

#by taking out the kg all that's left is numbers, but your computer was just told "out of these letters, take out 2 of them"
# so it doesn't realize anything about the data has changed until you tell it specifically to look at them AS numbers

In [26]:
pokedata['height_m'] = pokedata['height'].str.replace(' m', '', regex=False)
pokedata['height_m'] = pd.to_numeric(pokedata['height_m'])

pokedata.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,...,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage,weight_kg,height_m
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,...,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,Starter,6.9,0.71
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,...,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison,Middle,13.0,0.99
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,...,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison,Final,100.0,2.01
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,...,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None,Starter,8.5,0.61
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,...,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None,Middle,19.0,1.09

# now we're going to plot our scatterplot. It's going to be a little bit different this time.

For plotly go you may have noticed us using go.Pie or go.Bar before, that's specifying what graph you're making.

Now, we're going to build using go.Figure which is a constructor, **kind of like instead of buying a kit to build a table, and we're inside a hardware store making one now.**

the way we're going to do it is using (on the board)
## fig = go.Figure(data=[traces], layout=layout)

This way, we have the entire hardware store at our fingertips :D

In [27]:
# Cut if not enough time

traces = go.Scatter(x=pokedata['height_m'],
                    y=pokedata['weight_kg'],
                    mode='markers',
                    name='Lone')

layout = go.Layout(title=dict(text='Pokemon weight and height'),
    xaxis=dict(title='Weight (in kg)'),
    yaxis=dict(title='Height (in m)'),
    )

fig4 = go.Figure(data=[traces], layout=layout)

fig4.show()

#Now this plot is... deeply unhelpful, I basically don't know anything more than where I started,
# So I'm thinking, what if we broke up the pokemon into their evolutionary stages using multiple traces instead of 1?

#duplicate this Option+Shift+Down Arrow, or Alt+Shift+Down Arrow

In [28]:
trace1 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Lone']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Lone']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Lone']['name'],

                    name='Lone')
# we're going to set up 4 traces or plots in this figure now, mostly so that we can do more fun things later
# copy and paste this i beg you, and if you can use Find and Replace Even Better

trace2 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Starter']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Starter']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Starter']['name'],

                    name='Starter')

trace3 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Middle']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Middle']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Middle']['name'],

                    name='Middle')
                    

trace4 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Final']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Final']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Final']['name'],

                    name='Final')


layout = go.Layout(title=dict(text='Pokemon weight and height by Evolution Stage'),
    xaxis=dict(title='Weight (in kg)'),
    yaxis=dict(title='Height (in m)'),
    )

fig5 = go.Figure(data=[trace1, trace2, trace3, trace4], layout=layout)

#dont do this bit immediately, then add it
fig5.update_traces(mode='markers',
    marker=dict(size=10, opacity=.5)
)

fig5.show()

# Wow don't we feel fancy?? 
But what if we were FANCIER, Let's add more information to our hover text, like the pokemon's name and their types!

Before, we broke up our type Lists into two columns... Now we are going to smush them Back together but into a **string!**

(For reasons that we'll get into when it's relevant)

Using numpy where - which is just says if a certain condition is met do something and if it isn't met do a different thing, super similar to numpy select from the evolution stages code earlier

In [29]:
condition = pokedata['type1'].notna() & pokedata['type2'].notna()

pokedata['Types'] = np.where(condition, pokedata['type1'] + ' & ' + pokedata['type2'], pokedata['type1'])
pokedata.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,...,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage,weight_kg,height_m,Types
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,...,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,Starter,6.9,0.71,Grass & Poison
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,...,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison,Middle,13.0,0.99,Grass & Poison
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,...,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison,Final,100.0,2.01,Grass & Poison
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,...,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None,Starter,8.5,0.61,Fire
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,...,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None,Middle,19.0,1.09,Fire

In [30]:
#Copy from earlier
trace1 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Lone']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Lone']['weight_kg'],
                    #New bit! we're going to add custom data to say the name and text to say the type
                    #These are different because it is simpler to code and even though in the syntax it says text can be a list of strings it broke every single time and i couldn't find an example that used it
                    #custom data is quite literally just another variable i could use, there's like 3
                    customdata=pokedata[pokedata['evolution_stage'] == 'Lone']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Lone']['Types'],

                    name='Lone')

trace2 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Starter']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Starter']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Starter']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Starter']['Types'],

                    name='Starter')

trace3 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Middle']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Middle']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Middle']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Middle']['Types'],

                    name='Middle')
                    

trace4 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Final']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Final']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Final']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Final']['Types'],

                    name='Final')


layout = go.Layout(title=dict(text='Pokemon weight and height by Evolution Stage'),
    xaxis=dict(title='Weight (in kg)'),
    yaxis=dict(title='Height (in m)'),
    )

fig6 = go.Figure(data=[trace1, trace2, trace3, trace4], layout=layout)

#New bits! hovertemplate
fig6.update_traces(
    hovertemplate="<b>%{customdata}</b> "\
    "<br>%{text} Type"
    "<br>Weight: %{x}kg" \
    "<br>Height: %{y}m", 
    mode='markers',
    marker=dict(size=10, opacity=.5)
)

fig6.show()

#so now our scatterplot is a lot more useful because it follows the guideline of more information being discoverable, 
# what else might we add to add to the depth of the information present?
#Elle End

# Ananaya Start

## we're going to add buttons and dropdown capability!

In [31]:
trace1 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Lone']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Lone']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Lone']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Lone']['Types'],
                    #we're adding the colors now
                    marker_color='lightslategray',
                    name='Lone')

trace2 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Starter']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Starter']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Starter']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Starter']['Types'],
                    marker_color='plum',
                    name='Starter')

trace3 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Middle']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Middle']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Middle']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Middle']['Types'],
                    marker_color='mediumvioletred',
                    name='Middle')
                    

trace4 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Final']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Final']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Final']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Final']['Types'],
                    marker_color='indigo',
                    name='Final')


layout = go.Layout(title=dict(text='Pokemon weight and height by Evolution Stage'),
    xaxis=dict(title='Weight (in kg)'),
    yaxis=dict(title='Height (in m)'),
    showlegend=False
    )

fig7 = go.Figure(data=[trace1, trace2, trace3, trace4], layout=layout)

fig7.update_traces(
    hovertemplate="<b>%{customdata}</b> "\
    "<br>%{text} Type"
    "<br>Weight: %{x}kg" \
    "<br>Height: %{y}m", 
    mode='markers',
    marker=dict(size=10, opacity=.5)
)
#this is the new bit
fig7.update_layout(updatemenus = [dict(type = "buttons", direction = "left", x = 0.5, y = 1.15, showactive = True,
        buttons=list([dict(label = "Lone", method = "update", args = [{"visible" : [True, False, False, False]}]),
        dict(label = "Starter", method = "update", args = [{"visible" : [False, True, False, False]}]),
        dict(label = "Middle", method = "update", args = [{"visible" : [False, False, True, False]}]),
        dict(label = "Final", method = "update", args = [{"visible" : [False, False, False, True]}]),
        dict(label = "All", method = "update", args = [{"visible" : [True, True, True, True]}])]))
        ])

fig7.show()
#Ananaya Start

In [40]:
# Now the dropdown! It's just a matter of editing the update menus selector we already have
trace1 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Lone']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Lone']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Lone']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Lone']['Types'],
                    marker_color='lightslategray',
                    name='Lone')

trace2 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Starter']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Starter']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Starter']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Starter']['Types'],
                    marker_color='plum',
                    name='Starter')

trace3 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Middle']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Middle']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Middle']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Middle']['Types'],
                    marker_color='mediumvioletred',
                    name='Middle')
                    

trace4 = go.Scatter(x=pokedata[pokedata['evolution_stage'] == 'Final']['height_m'],
                    y=pokedata[pokedata['evolution_stage'] == 'Final']['weight_kg'],
                    customdata=pokedata[pokedata['evolution_stage'] == 'Final']['name'],
                    text=pokedata[pokedata['evolution_stage'] == 'Final']['Types'],
                    marker_color='indigo',
                    name='Final')


layout = go.Layout(title=dict(text='Pokemon weight and height by Evolution Stage'),
    xaxis=dict(title='Weight (in kg)'),
    yaxis=dict(title='Height (in m)'),
    showlegend=False
    )

fig8 = go.Figure(data=[trace1, trace2, trace3, trace4], layout=layout)
 
fig8.update_traces(
    hovertemplate="<b>%{customdata}</b> "\
    "<br>%{text} Type"
    "<br>Weight: %{x}kg" \
    "<br>Height: %{y}m",
    mode='markers',
    marker=dict(size=10, opacity=.35)
)
 
fig8.update_layout (updatemenus = [dict(direction = "down", showactive = True, x = 0.5, xanchor = "left", y = 1.15, yanchor = "top",
        buttons=list([dict(label = "All", method = "update", args = [{"visible" : [True, True, True, True]}]),
        dict(label = "Starter", method = "update", args = [{"visible" : [False, True, False, False]}]),
        dict(label = "Middle", method = "update", args = [{"visible" : [False, False, True, False]}]),
        dict(label = "Final", method = "update", args = [{"visible" : [False, False, False, True]}]),
        dict(label = "Lone", method = "update", args = [{"visible" : [True, False, False, False]}])]))
        ])
 
 
fig8.show()

# End